name: only_dart
description: A Command Line Application To Convert en to any Language.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  translator:
    path: ./translator-0.1.7
  compute: ^1.0.2

dev_dependencies:
  lints: ^2.0.1
