name: translator
version: 0.1.7
description: A free and unlimited Google Translate API for Dart. You can use it for translate strings and text for educational purpose.
#author: Gabriel N. Pacheco <gabrielpacheco23@live.com>
homepage: https://github.com/gabrielpacheco23/google-translator
publish_to: none

dependencies:
  http: ^0.13.5

environment:
  sdk: ">=2.12.0 <3.0.0"
